twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_sdb_hash: '%app_sdb_hash%'
when@test:
    twig:
        strict_variables: true
